=== DongxianGU/Accumulating-process/language/java/basis/day08/a_dtd/m.dtd
<!--参数实体 主要给DTD文件使用-->
        <!ENTITY % strs "heading | from ">
<!ELEMENT note (title,from?,to+,heading*,body+)>
        <!ELEMENT to      EMPTY>
        <!ELEMENT from    (#PCDATA)>
        <!ELEMENT heading (#PCDATA)>
        <!ELEMENT body    (#PCDATA)>
        <!ELEMENT title   (%strs;)>
        <!ATTLIST to
                id ID #REQUIRED
                name CDATA #FIXED "name"
                age CDATA #IMPLIED
                >
<!--引用实体 直接通过 &元素 主要被xml应用-->
<!ENTITY entity "i'm an entity">

=== DongxianGU/Accumulating-process/language/java/basis/day08/a_dtd/m.xml
<?xml version='1.0' ?>
<!DOCTYPE note SYSTEM 'm.dtd'>
<!--dtd 约束 标签要和定义的顺序一致-->
<note>
    <title>
        <heading>aa</heading>
    </title>
    <to id="aa" name="name" age="12"></to>
    <to id="ss1" name="name"></to>
    <to id="ss"  age="&entity;"></to>
    <heading>ss</heading>
    <heading>ss</heading>
    <heading>ss</heading>
    <body>sss</body>
    <body>ss</body>
</note>
